language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --features testbed,ci --verbose
  - cargo test --features testbed,ci --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
after_success:
- test $TRAVIS_BRANCH = "master" &&  bash ci/publish_docs.sh