[package]
name = "newton-examples"
version = "0.1.0"
authors = ["german gomez <germangb42@gmail.com>"]
edition = "2018"

[dependencies]
newton = { path = "../newton", features = ["sandbox"] }
cgmath = "0.16"
